[build]
  # Directory to build from (relative to repo root)
  base = "client"
  
  # Build command
  command = "npm run build"
  
  # Directory to publish (build output) - relative to base
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # API URL for frontend
  VITE_API_BASE_URL = "https://spacelearn-backend.onrender.com/api"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"